#include <lib/trap.h>
#include <lib/debug.h>
#include <lib/string.h>
#include <dev/intr.h>
#include "import.h"

#define KERN_INFO_CPU(str, idx) \
    if (idx == 0) KERN_INFO("[BSP KERN] " str); \
    else KERN_INFO("[AP%d KERN] " str, idx);

int inited = FALSE;

trap_cb_t TRAP_HANDLER[NUM_CPUS][256];

void trap_init_array(void)
{
    KERN_ASSERT(inited == FALSE);
    memzero(&TRAP_HANDLER, sizeof(trap_cb_t) * 8 * 256);
    inited = TRUE;
}

void trap_handler_register(int cpu_idx, int trapno, trap_cb_t cb)
{
    KERN_ASSERT(0 <= cpu_idx && cpu_idx < 8);
    KERN_ASSERT(0 <= trapno && trapno < 256);
    KERN_ASSERT(cb != NULL);

    TRAP_HANDLER[cpu_idx][trapno] = cb;
}

void trap_init(unsigned int cpu_idx)
{
    if (cpu_idx == 0) {
        trap_init_array();
    }

    KERN_INFO_CPU("Register trap handlers...\n", cpu_idx);

    // TODO: for CPU # [cpu_idx], register appropriate trap handler for each trap number,
    // with trap_handler_register function defined above.

    /* (0 ~ 31) Exceptions: reserved by hardware  */
    trap_handler_register(cpu_idx, T_DIVIDE, exception_handler); /* divide error */
    trap_handler_register(cpu_idx, T_DEBUG, exception_handler);  /* debug exception */
    trap_handler_register(cpu_idx, T_NMI, exception_handler);    /* non-maskable interrupt */
    trap_handler_register(cpu_idx, T_BRKPT, exception_handler);  /* breakpoint */
    trap_handler_register(cpu_idx, T_OFLOW, exception_handler);  /* overflow */
    trap_handler_register(cpu_idx, T_BOUND, exception_handler);  /* bounds check */
    trap_handler_register(cpu_idx, T_ILLOP, exception_handler);  /* illegal opcode */
    trap_handler_register(cpu_idx, T_DEVICE, exception_handler); /* device not available */
    trap_handler_register(cpu_idx, T_DBLFLT, exception_handler); /* double fault */
    trap_handler_register(cpu_idx, T_COPROC, exception_handler); /* reserved (not generated by recent processors) */
    trap_handler_register(cpu_idx, T_TSS, exception_handler);    /* invalid task switch segment */
    trap_handler_register(cpu_idx, T_SEGNP, exception_handler);  /* segment not present */
    trap_handler_register(cpu_idx, T_STACK, exception_handler);  /* stack exception */
    trap_handler_register(cpu_idx, T_GPFLT, exception_handler);  /* general protection fault */
    trap_handler_register(cpu_idx, T_PGFLT, exception_handler);  /* page fault                                            => dispatched within */
    trap_handler_register(cpu_idx, T_RES, exception_handler);    /* reserved */
    trap_handler_register(cpu_idx, T_FPERR, exception_handler);  /* floating point error */
    trap_handler_register(cpu_idx, T_ALIGN, exception_handler);  /* alignment check */
    trap_handler_register(cpu_idx, T_MCHK, exception_handler);   /* machine check */
    trap_handler_register(cpu_idx, T_SIMD, exception_handler);   /* SIMD floating point exception */
    trap_handler_register(cpu_idx, T_SECEV, exception_handler);  /* Security-sensitive event */

    /* (32 ~ 47) ISA interrupts: used by i8259 */
    /* (48 ~ 55) reserved for IOAPIC extended interrupts */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_TIMER, interrupt_handler);      /* 8253 Programmable Interval Timer (PIT) => dispatched within */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_KBD, interrupt_handler);        /* Keyboard interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_SLAVE, interrupt_handler);      /* cascaded to slave 8259 */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_SERIAL24, interrupt_handler);   /* Serial (COM2 and COM4) interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_SERIAL13, interrupt_handler);   /* Serial (COM1 and COM4) interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_LPT2, interrupt_handler);       /* Parallel (LPT2) interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_FLOPPY, interrupt_handler);     /* Floppy interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_SPURIOUS, interrupt_handler);   /* Spurious interrupt or LPT1 interrupt   => dispatched within */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_RTC, interrupt_handler);        /* RTC interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_MOUSE, interrupt_handler);      /* Mouse interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_COPROCESSOR, interrupt_handler);/* Math coprocessor interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_IDE1, interrupt_handler);       /* IDE disk controller 1 interrupt */
    trap_handler_register(cpu_idx, T_IRQ0 + IRQ_IDE2, interrupt_handler);       /* IDE disk controller 2 interrupt */

    /* (48) System Call interrupt */
    trap_handler_register(cpu_idx, T_SYSCALL, syscall_dispatch); // dispatched within

    KERN_INFO_CPU("Done.\n", cpu_idx);
    KERN_INFO_CPU("Enabling interrupts...\n", cpu_idx);

    /* enable interrupts */
    intr_enable(IRQ_TIMER, cpu_idx);
    intr_enable(IRQ_KBD, cpu_idx);
    intr_enable(IRQ_SERIAL13, cpu_idx);

    KERN_INFO_CPU("Done.\n", cpu_idx);
}
